# 1. Import libraries

In [1]:
try:
  # Colab only
  %tensorflow_version 2.x
except Exception:
    pass

In [2]:
# !pip install konlpy

In [3]:
# !pip install gensim

In [4]:
#colab에서 실행 중이라면...
# !git clone https://github.com/hukim1112/comment_classifier.git
# import os
# os.chdir('/content/comment_classifier')

In [5]:
import tensorflow as tf
from konlpy.tag import Okt
from collections import Counter
import pandas as pd
import numpy as np
import gensim
from matplotlib import pyplot as plt


keras = tf.keras
t = Okt()

# 2. fit tokenizer to our datasets

In [37]:
from vectorizer import BaseVectorizer
vectorizer = BaseVectorizer(t.morphs)
tokenizer = BaseVectorizer(t.morphs)

In [38]:
df = pd.read_csv('Entitytest.csv',encoding='CP949')

In [39]:
df[0:1]

word entity
0  빨간색  color

In [40]:
tokenizer.fit(df['word'].values)

scanning was done                                        
105 terms are recognized


In [41]:
tokenizer.vocabulary_

{'_PAD_': 0,
 '_UNK_': 1,
 '_STA_': 2,
 '_EOS_': 3,
 '색': 4,
 '보라색': 5,
 '공': 6,
 '과자': 7,
 '지갑': 8,
 '위': 9,
 '아래': 10,
 '맨': 11,
 '빨간색': 12,
 '파랑색': 13,
 '빨강': 14,
 '파란색': 15,
 '주황색': 16,
 '노란색': 17,
 '노랑': 18,
 '초록색': 19,
 '녹색': 20,
 '연두색': 21,
 '남색': 22,
 '자주색': 23,
 '하늘색': 24,
 '연': 25,
 '분홍색': 26,
 '청록색': 27,
 '청색': 28,
 '적색': 29,
 '갈색': 30,
 '네이비': 31,
 '자동차': 32,
 '축구공': 33,
 '농구공': 34,
 '피구': 35,
 '럭비공': 36,
 '야구공': 37,
 '테니스공': 38,
 '장난감': 39,
 '의자': 40,
 '책': 41,
 '책상': 42,
 '컵': 43,
 '상자': 44,
 '박스': 45,
 '게임기': 46,
 '컴퓨터': 47,
 '텔레비전': 48,
 '티비': 49,
 '가방': 50,
 '양말': 51,
 '패딩': 52,
 '외투': 53,
 '티셔츠': 54,
 '셔츠': 55,
 '바지': 56,
 '청바지': 57,
 '핸드폰': 58,
 '휴대폰': 59,
 '키': 60,
 '보드': 61,
 '마우스': 62,
 '모니터': 63,
 '노트북': 64,
 '공책': 65,
 '오른쪽': 66,
 '왼쪽': 67,
 '좌회전': 68,
 '우회': 69,
 '전': 70,
 '좌측': 71,
 '우측': 72,
 '저기': 73,
 '여기': 74,
 '저쪽': 75,
 '동쪽': 76,
 '서쪽': 77,
 '남쪽': 78,
 '북쪽': 79,
 '동': 80,
 '서': 81,
 '남': 82,
 '북': 83,
 '옆': 84,
 '안': 85,
 '붉': 86,
 '은색': 87,
 '푸른색': 88,


In [43]:
tokenizer.get_char2idx()

In [46]:
wordvoca = tokenizer.char2idx

In [70]:
wordvoca

{'_PAD_': 0,
 '_UNK_': 1,
 '_': 2,
 'P': 3,
 'A': 4,
 'D': 5,
 'U': 6,
 'N': 7,
 'K': 8,
 'S': 9,
 'T': 10,
 'E': 11,
 'O': 12,
 '색': 13,
 '보': 14,
 '라': 15,
 '공': 16,
 '과': 17,
 '자': 18,
 '지': 19,
 '갑': 20,
 '위': 21,
 '아': 22,
 '래': 23,
 '맨': 24,
 '빨': 25,
 '간': 26,
 '파': 27,
 '랑': 28,
 '강': 29,
 '란': 30,
 '주': 31,
 '황': 32,
 '노': 33,
 '초': 34,
 '록': 35,
 '녹': 36,
 '연': 37,
 '두': 38,
 '남': 39,
 '하': 40,
 '늘': 41,
 '분': 42,
 '홍': 43,
 '청': 44,
 '적': 45,
 '갈': 46,
 '네': 47,
 '이': 48,
 '비': 49,
 '동': 50,
 '차': 51,
 '축': 52,
 '구': 53,
 '농': 54,
 '피': 55,
 '럭': 56,
 '야': 57,
 '테': 58,
 '니': 59,
 '스': 60,
 '장': 61,
 '난': 62,
 '감': 63,
 '의': 64,
 '책': 65,
 '상': 66,
 '컵': 67,
 '박': 68,
 '게': 69,
 '임': 70,
 '기': 71,
 '컴': 72,
 '퓨': 73,
 '터': 74,
 '텔': 75,
 '레': 76,
 '전': 77,
 '티': 78,
 '가': 79,
 '방': 80,
 '양': 81,
 '말': 82,
 '패': 83,
 '딩': 84,
 '외': 85,
 '투': 86,
 '셔': 87,
 '츠': 88,
 '바': 89,
 '핸': 90,
 '드': 91,
 '폰': 92,
 '휴': 93,
 '대': 94,
 '키': 95,
 '마': 96,
 '우': 97,
 '모': 98,
 '트': 99,
 '

# 3. data preprocessing

In [47]:
label_to_id = {t:i for i,t in enumerate(df.entity.unique())}
id_to_label = {i:t for i,t in enumerate(df.entity.unique())}

In [48]:
print(label_to_id)

{'color': 0, 'thing': 1, 'loc': 2}


In [49]:
# df.intent = df.intent.map(lambda x : label_index[x])
# print(df.head(10))

In [97]:
MAX_LENGTH = 10
def tokenize_by_char(words,labels):
    inputs , outputs = [], []
    for word,label in zip(words,labels):
        tempword = []
        tempnum = []
        for i in range(len(word)):
            tempword.append(word[i])
        for i in tempword:
            tempnum.append(wordvoca[i])
        if len(tempnum) <= MAX_LENGTH:
            inputs.append(tempnum)
            outputs.append(label_to_id[label])
    padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
        inputs, maxlen=MAX_LENGTH, padding='post', 
        value = tokenizer.char2idx['_PAD_']) # value = 0
  
    return padded_inputs, outputs
            

In [98]:
MAX_LENGTH = 10
def tokenize_and_filter(sentences, labels):
    inputs, outputs = [], []
    a = 0
    for sentence, label in zip(sentences, labels):
    # tokenize sentence
        tokenized_sentence = tokenizer.encode_a_doc_to_list(sentence)
#         print(tokenized_sentence)
#         print(a)
    # check tokenized sentence max length
        if len(tokenized_sentence) <= MAX_LENGTH:
            inputs.append(tokenized_sentence)
#             print(inputs)
#             print("input append")
            outputs.append(label_to_id[label])
#             print(outputs)
        a+=1
  # pad tokenized sentences
    padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
        inputs, maxlen=MAX_LENGTH, padding='post', 
        value = tokenizer.vocabulary_['_PAD_']) # value = 0
  
    return padded_inputs, outputs

In [99]:
inputs, outputs = tokenize_and_filter(df.word, df.entity)

[12]
0
[[12]]
[0]
[13]
1
[[12], [13]]
[0, 0]
[14, 4]
2
[[12], [13], [14, 4]]
[0, 0, 0]
[15]
3
[[12], [13], [14, 4], [15]]
[0, 0, 0, 0]
[16]
4
[[12], [13], [14, 4], [15], [16]]
[0, 0, 0, 0, 0]
[17]
5
[[12], [13], [14, 4], [15], [16], [17]]
[0, 0, 0, 0, 0, 0]
[18, 4]
6
[[12], [13], [14, 4], [15], [16], [17], [18, 4]]
[0, 0, 0, 0, 0, 0, 0]
[19]
7
[[12], [13], [14, 4], [15], [16], [17], [18, 4], [19]]
[0, 0, 0, 0, 0, 0, 0, 0]
[20]
8
[[12], [13], [14, 4], [15], [16], [17], [18, 4], [19], [20]]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[21]
9
[[12], [13], [14, 4], [15], [16], [17], [18, 4], [19], [20], [21]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[22]
10
[[12], [13], [14, 4], [15], [16], [17], [18, 4], [19], [20], [21], [22]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[23]
11
[[12], [13], [14, 4], [15], [16], [17], [18, 4], [19], [20], [21], [22], [23]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[5]
12
[[12], [13], [14, 4], [15], [16], [17], [18, 4], [19], [20], [21], [22], [23], [5]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[24

In [100]:
inputs, outputs = tokenize_by_char(df.word, df.entity)

In [101]:
print('encoded input : ', inputs[0], 'label : ', outputs[0], 'original input sentence : ', tokenizer.decode_from_list(inputs[0]))

encoded input :  [25 26 13  0  0  0  0  0  0  0] label :  0 original input sentence :  ['연', '분홍색', '파랑색', '_PAD_', '_PAD_', '_PAD_', '_PAD_', '_PAD_', '_PAD_', '_PAD_']


In [103]:
BATCH_SIZE = 16
BUFFER_SIZE = 7836

# decoder inputs use the previous target as input
# remove START_TOKEN from targets
dataset = tf.data.Dataset.from_tensor_slices((inputs, outputs))

dataset = dataset.cache()
dataset = dataset.shuffle(BUFFER_SIZE)
dataset = dataset.batch(BATCH_SIZE)
dataset = dataset.prefetch(tf.data.experimental.AUTOTUNE)

In [104]:
dataset

<PrefetchDataset shapes: ((None, 10), (None,)), types: (tf.int32, tf.int32)>

In [105]:
for x, y in dataset.take(1):
    print(x, y)
    print('-----------------------------------------------')
    print(x.shape, y.shape)

tf.Tensor(
[[ 97 106  77   0   0   0   0   0   0   0]
 [ 65   0   0   0   0   0   0   0   0   0]
 [ 54  53  16   0   0   0   0   0   0   0]
 [ 44  35  13   0   0   0   0   0   0   0]
 [ 89  19   0   0   0   0   0   0   0   0]
 [ 57  53  16   0   0   0   0   0   0   0]
 [ 52  53  16   0   0   0   0   0   0   0]
 [ 46  13   0   0   0   0   0   0   0   0]
 [ 79  80   0   0   0   0   0   0   0   0]
 [ 31  32  13   0   0   0   0   0   0   0]
 [ 22  48  83  91   0   0   0   0   0   0]
 [ 96  97  60   0   0   0   0   0   0   0]
 [ 25  26   0   0   0   0   0   0   0   0]
 [105 106  77   0   0   0   0   0   0   0]
 [ 24  22  23   0   0   0   0   0   0   0]
 [ 37  14  15  13   0   0   0   0   0   0]], shape=(16, 10), dtype=int32) tf.Tensor([2 1 1 0 1 1 1 0 1 0 1 1 0 2 2 0], shape=(16,), dtype=int32)
-----------------------------------------------
(16, 10) (16,)


# 4. model design

In [112]:
print(len(label_to_id.values()))

3


In [114]:
len(wordvoca)

130

In [115]:
def get_model():
    model = tf.keras.Sequential([
    tf.keras.layers.Embedding(len(wordvoca), 64),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(len(label_to_id.values()), activation='softmax')
])
    LEARNING_RATE = 0.001
    model.compile(optimizer=tf.keras.optimizers.Adam(LEARNING_RATE),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=[tf.keras.metrics.sparse_categorical_accuracy])
    return model

In [116]:
model = get_model()

In [117]:
# LEARNING_RATE = 0.001

In [118]:
# model.compile(optimizer=tf.keras.optimizers.Adam(LEARNING_RATE),
#               loss=tf.keras.losses.sparse_categorical_crossentropy,
#               metrics=[tf.keras.metrics.sparse_categorical_accuracy])

In [120]:
model.fit(dataset, epochs=10)

Epoch 1/10
7/7 [==============================] - 0s 8ms/step - loss: 0.1469 - sparse_categorical_accuracy: 0.9596
Epoch 2/10
7/7 [==============================] - 0s 7ms/step - loss: 0.2377 - sparse_categorical_accuracy: 0.8990
Epoch 3/10
7/7 [==============================] - 0s 7ms/step - loss: 0.1242 - sparse_categorical_accuracy: 0.9596
Epoch 4/10
7/7 [==============================] - 0s 7ms/step - loss: 0.0553 - sparse_categorical_accuracy: 0.9798
Epoch 5/10
7/7 [==============================] - 0s 7ms/step - loss: 0.0251 - sparse_categorical_accuracy: 1.0000
Epoch 6/10
7/7 [==============================] - 0s 7ms/step - loss: 0.0091 - sparse_categorical_accuracy: 1.0000
Epoch 7/10
7/7 [==============================] - 0s 6ms/step - loss: 0.0068 - sparse_categorical_accuracy: 1.0000
Epoch 8/10
7/7 [==============================] - 0s 7ms/step - loss: 0.0028 - sparse_categorical_accuracy: 1.0000
Epoch 9/10
7/7 [==============================] - 0s 7ms/step - loss: 0.0021 - s

In [131]:
def question_processing(sentences):
    MAX_LENGTH = 10
    inputs = []
    for sentence in sentences:
        # tokenize sentence
        tokenized_sentence = tokenizer.encode_a_doc_to_list(sentence)
        print(tokenized_sentence)
        # check tokenized sentence max length
        if len(tokenized_sentence) <= MAX_LENGTH:
            inputs.append(tokenized_sentence)
        else:
            print('입력이 너무 길어요.')
    # pad tokenized sentences
    padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
    inputs, maxlen=MAX_LENGTH, padding='post', 
    value = tokenizer.char2idx['_PAD_']) # value = 0
    return padded_inputs

In [140]:
def word_question_procession(words):
    MAX_LENGTH = 10
    inputs = [] 
    for word in words:
        tempword = []
        tempnum = []
        for i in range(len(word)):
            tempword.append(word[i])
        for i in tempword:
            try:
                tempnum.append(wordvoca[i])
            except:
                pass
        if len(tempnum) <= MAX_LENGTH:
            inputs.append(tempnum)
        else:
            print("단어의 길이가 너무 길어요")
    padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
    inputs, maxlen=MAX_LENGTH, padding='post', 
    value = tokenizer.char2idx['_PAD_']) # value = 0
    return padded_inputs

In [136]:
input_sentence = question_processing(['빨간색','루삥뽕','휴지','파랑색','비','무지개색','오른쪽','노란색','유니폼','상자','옆','위'
                                     ])

[12]
[]
[100]
[13]
[]
[4]
[66]
[17]
[]
[44]
[84]
[9]


In [146]:
input_sentence = word_question_procession(['빨간색','휴지','파랑색','비','무지개색','오른쪽','노란색','유니폼','상자','옆','위','뿡뿡색'
                                     ])

In [147]:
model.predict(input_sentence)

array([[9.9998760e-01, 3.7207014e-06, 8.7071894e-06],
       [9.6180247e-07, 9.9987519e-01, 1.2387960e-04],
       [9.9998724e-01, 3.6542756e-06, 9.0944723e-06],
       [1.1489319e-05, 9.9463886e-01, 5.3496733e-03],
       [1.1873854e-01, 7.3800516e-01, 1.4325629e-01],
       [7.3694269e-04, 1.9393369e-03, 9.9732363e-01],
       [9.9998331e-01, 7.6934866e-06, 8.9451787e-06],
       [1.8423278e-06, 9.9971730e-01, 2.8087327e-04],
       [1.2882176e-06, 9.9990952e-01, 8.9181274e-05],
       [3.6763020e-03, 1.7349913e-03, 9.9458873e-01],
       [8.6124090e-04, 1.4980709e-03, 9.9764073e-01],
       [9.9961698e-01, 2.5428884e-05, 3.5766669e-04]], dtype=float32)

In [150]:
prediction = np.argmax(model.predict(input_sentence), axis=1)
print(prediction)

[0 1 0 1 1 2 0 1 1 2 2 0]


In [151]:
for p in prediction:
    print(id_to_label[p])

color
thing
color
thing
thing
loc
color
thing
thing
loc
loc
color


In [152]:
# 모델 저장하기
model.save('entitytestmodel.h5')
# 모델 불러오기
tempmodel = keras.models.load_model('entitytestmodel.h5')
tempmodel.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, None, 64)          8320      
_________________________________________________________________
bidirectional_3 (Bidirection (None, 128)               66048     
_________________________________________________________________
dense_6 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 195       
Total params: 82,819
Trainable params: 82,819
Non-trainable params: 0
_________________________________________________________________


In [34]:
tempmodel.predict(input_sentence)

array([[9.5373678e-01, 8.5971355e-05, 4.6177287e-02],
       [5.6485320e-08, 9.9999642e-01, 3.6223596e-06],
       [9.3436652e-01, 1.3932100e-04, 6.5494195e-02],
       [9.9562109e-04, 9.2088032e-01, 7.8124106e-02],
       [9.4302708e-01, 1.3661891e-04, 5.6836307e-02],
       [3.1226311e-02, 4.0562011e-02, 9.2821169e-01],
       [8.8532829e-01, 3.3773883e-04, 1.1433393e-01],
       [9.9562109e-04, 9.2088032e-01, 7.8124106e-02],
       [9.6571647e-08, 9.9999440e-01, 5.5115884e-06],
       [2.4339160e-02, 5.0067291e-02, 9.2559355e-01],
       [2.3435676e-02, 6.0822763e-02, 9.1574150e-01]], dtype=float32)

In [35]:
list(np.argmax(model.predict(input_sentence), axis=1))

[0, 1, 0, 1, 0, 2, 0, 1, 1, 2, 2]

In [36]:
for p in prediction:
    print(id_to_label[p])

color
thing
color
thing
color
loc
color
thing
thing
loc
loc


In [37]:
del model

# 데이터 추가해보기

In [ ]:
names = ['안중근', '이순신', '세종대왕', '김광석', '아이유', '에미넴', '이건희', '고아라', '유재석', '한석희', '최민성']
def question_generator(names):
    question = []
    for name in names:
        s1 = name+'는 어떤 분이야?'
        s2 = name+'은 어떤 사람이니?'
        s3 = name+'이란 사람에 대해 궁금해'
        question = question+[s1, s2, s3]
    return question
question = question_generator(names)

In [ ]:
question

In [ ]:
new_data = {'question' : question, 'intent' : ['인물']*len(question)}
add_df = pd.DataFrame(new_data, columns=('question', 'intent'))

In [ ]:
add_df.head(5)

In [ ]:
print(len(df), len(add_df))

In [ ]:
new_df = pd.concat([df, add_df])
print(len(new_df))

In [ ]:
tokenizer.fit(new_df['question'].values)

In [ ]:
new_inputs, new_outputs = tokenize_and_filter(new_df.question, new_df.intent)

BATCH_SIZE = 16
BUFFER_SIZE = 7836

# decoder inputs use the previous target as input
# remove START_TOKEN from targets
dataset = tf.data.Dataset.from_tensor_slices((new_inputs, new_outputs))

dataset = dataset.cache()
dataset = dataset.shuffle(BUFFER_SIZE)
dataset = dataset.batch(BATCH_SIZE)
dataset = dataset.prefetch(tf.data.experimental.AUTOTUNE)

In [ ]:
new_model = get_model()
LEARNING_RATE = 0.0001
new_model.compile(optimizer=tf.keras.optimizers.Adam(LEARNING_RATE),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=[tf.keras.metrics.sparse_categorical_accuracy])
new_model.fit(dataset, epochs=10)

In [ ]:
input_sentence = question_processing(['서울 날씨 어때?', 
                                      '나는 전주 날씨 궁금함',
                                      '안중근 의사는 누구야?',
                                      '박소희는 어떤 사람인지 궁금해.',
                                      '명동 맛있는 음식점 있니?'
                                     ])

In [ ]:
new_model.predict(input_sentence)

In [ ]:
prediction = np.argmax(new_model.predict(input_sentence), axis=1)

In [ ]:
for p in prediction:
    print(id_to_label[p])

In [216]:
from konlpy.tag import Kkma
from konlpy.utils import pprint
kkma = Kkma()

In [217]:

def 형태소분석(text):
    형태소 = kkma.pos(text)
    명사 = []
    for i in 형태소:
        if i[1] == 'NNG':
            명사.append(i[0])
        else:
            pass
    return 명사

def entity분석(명사):
    inputdata = question_processing(명사)
    prediction = list(np.argmax(tempmodel.predict(inputdata),axis=1))
    print(명사)
    print(prediction)
    result = {}
    for a,b in zip(명사,prediction):
        if b == 0:
            result[a] = 'color'
        elif b == 1:
            result[a] = 'thing'
        elif b == 2:
            result[a] = 'loc'
    return result  


In [221]:
tempmodel = keras.models.load_model('entitytestmodel.h5')
noun = 형태소분석('빨간색 공책 녹색 상자 안에 넣어')
result = entity분석(noun)

['빨간색', '공책', '녹색', '상자', '안']
[0, 1, 0, 1, 2]


In [222]:
result

{'빨간색': 'color', '공책': 'thing', '녹색': 'color', '상자': 'thing', '안': 'loc'}